language: python
branches:
  only:
  - master
  - "/^v\\d+.\\d+(.\\d+)?(-\\S*)?$/"
  - "/^feat\\/.*$/"
matrix:
  include:
  - name: docker
    os: linux
    env: BUILD_DOCKER=true
    services:
      - docker

  - name: "Linux Python 3.5"
    os: linux
    python: '3.5'

  - name: "Linux Python 3.6"
    os: linux
    python: '3.6'

  - name: "Linux Python 3.7"
    os: linux
    python: 3.7-dev

  - name: "OSX Python 3.5"
    os: osx
    language: generic
    env: PYTHON=3.5.6

  - name: "OSX Python 3.6"
    os: osx
    language: generic
    env: PYTHON=3.6.6

  - name: "OSX Python 3.7"
    os: osx
    language: generic
    env: PYTHON=3.7.0


before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
    choco install miniconda3 --params="'/AddToPath:1'"
    conda config --add channels conda-forge
    conda create -n py$PYTHON python=$PYTHON
    activate py$PYTHON
  fi

install:
  - pip install pipenv
  - pipenv install --dev

script: |
  if [ "$BUILD_DOCKER" == "true" ]; then
    docker build -t pushbullet-cli .
  else
    pipenv run pytest --cov=pushbullet_cli
  fi

after_success:
  - codecov

deploy:
  - provider: pypi
    user: gustavokatel
    password:
      secure: wceJMzwNsCqcUhy+dxtex9dR/fMEqSvJaPRaGcAkegikNfZEhjSngWIqmuiiNFxxvOgsWouU0uQLsZYaFV7tTmn9MP+3RTjjYjIXmaqTTqGbKGzbyFDJgc1xu3a5dyEK1OGUL3a6JWfOt1v+6x3Y+zCMox1NLoF5kEjwab1Hbkqr6PYDcCQarE9sj8OG6C6Vg8DGkzzMetfeWPsvOHA+viBaQQpsAsawtZU/XiupEid6PaJJ5WGMD5FG/qgPs/mmnwysEZBc+G5CEYeCu1E0J+i4xSE5IjQUG5xRcBIezgO06BldtmDSKMERo3pzdDJGmhYC+5QtsUGaJz2HuOJpRZ55yP0Non7s6+1GODw97aSdnC7yzEPbKo61x8q8LZN3dWGciWARCfcwQBWZRBgZqMqYdaKN3Bk96Ai6DQRdctcPjvoXzKLtU4eJawP24OcC6c/kkNqc6e2tVactSbfGe+FJtPHlyoYwIVsTP2Wcv7CPzGBqAxy4VHoCiMTNFwp9MsK854bi3/fpiML0beyUEBG2tx+9KCxGfNKhIA0hoQlIkuWl4kMOeMrM9iw5RVT1js2v+/uGDJJ8cHDfUPqCwhSsjYSkQrbm9r2C/gXsV56jZytz6XxGsesuhvuIRNdEYoPvYNb4lOixVdjE9qCuoFzio58XqWdO0M0ey3Jb+Jo=
    on:
      tags: true
    skip_existing: true

  - provider: script
    script: bash .ci/deploy-docker.sh
    on:
      tags: true
      branch: master

notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
    urls:
      secure: C35gKaP63zrNdFCw9ln6Y095u92q9hnAsqEsR2JpD1/U+WM1fBlrX1oOilXGH3e8/aTB2tKiYN3AaDPcG2raneBtaoU2caDIwo1MUGbO4HlZBiH73WfWLyTUoaEyqr/Q1+A0WnlTS04w4hXxSrvtkq89BDDN0AMD8d1hu7Qv2y0=
    on_success: always
    on_failure: always
    on_error: always
